# Generated by Django 5.2 on 2025-04-27 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_evaluation_score_profile_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedProfilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('share', 'Share'), ('delete', 'Delete')], max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='profiles.profile')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('profile', 'shared_with', 'permissions')},
            },
        ),
        migrations.DeleteModel(
            name='ProfileShare',
        ),
    ]
