# Generated by Django 5.2 on 2025-04-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_sharedprofilepermission_delete_profileshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
