# Generated by Django 5.2 on 2025-07-03 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProfileDomain", "0001_initial"),
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goal",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="subobjective",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="goal",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goals",
                to="ProfileDomain.profiledomain",
            ),
        ),
        migrations.AddField(
            model_name="subobjective",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
    ]
