# Generated by Django 5.2 on 2025-07-12 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProfileDomain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('comentaire', models.TextField(blank=True, null=True)),
                ('is_modified', models.BooleanField(default=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('etat', models.CharField(choices=[('ACQUIS', 'Acquis'), ('PARTIEL', 'Partiel'), ('NON_ACQUIS', 'Non Acquis'), ('NON_COTE', 'Non Coté')], default='NON_COTE', max_length=10)),
                ('profile_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ProfileDomain.profiledomain')),
            ],
            options={
                'db_table': 'profile_item',
            },
        ),
    ]
