# Generated by Django 5.2 on 2025-07-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileItem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileitem',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
