# Generated by Django 5.2 on 2025-06-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileItem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileitem',
            name='comentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
