# Generated by Django 5.2 on 2025-05-01 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('template_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='profiles.profile')),
                ('template_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='template_data.templatecategory')),
            ],
            options={
                'db_table': 'profile_category',
            },
        ),
        migrations.CreateModel(
            name='ProfileDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='profile_data.profilecategory')),
                ('template_domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='template_data.templatedomain')),
            ],
            options={
                'db_table': 'profile_domain',
            },
        ),
        migrations.CreateModel(
            name='ProfileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_modified', models.BooleanField(default=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('profile_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='profile_data.profiledomain')),
                ('template_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='template_data.templateitem')),
            ],
            options={
                'db_table': 'profile_item',
            },
        ),
    ]
