# Generated by Django 5.2 on 2025-05-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledomain',
            name='acquis_percentage',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='profiledomain',
            name='item_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='profileitem',
            name='etat',
            field=models.CharField(choices=[('ACQUIS', 'Acquis'), ('PARTIEL', 'Partiel'), ('NON_ACQUIS', 'Non Acquis'), ('NON_COTE', 'Non Coté')], default='NON_COTE', max_length=10),
        ),
    ]
