# Generated by Django 5.2 on 2025-11-11 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProfileCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('item_count', models.PositiveIntegerField(default=0, editable=False)),
                ('acquis_percentage', models.FloatField(default=0.0, editable=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('last_evaluation_date', models.DateField(auto_now=True)),
                ('profile_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='ProfileCategory.profilecategory')),
            ],
            options={
                'db_table': 'profile_domain',
            },
        ),
    ]
