# Generated by Django 5.2 on 2025-08-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
