# Generated by Django 5.2 on 2025-08-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Note Content (Arabic)'),
        ),
    ]
