# Generated by Django 5.2 on 2025-05-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatedomain',
            old_name='category',
            new_name='template_category',
        ),
        migrations.RenameField(
            model_name='templateitem',
            old_name='domain',
            new_name='template_domain',
        ),
        migrations.AddField(
            model_name='templatedomain',
            name='level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='templateitem',
            name='code',
            field=models.CharField(blank=True, choices=[('A', 'Acquis'), ('P', 'Partiel'), ('N', 'Non Acquis'), ('X', 'Non Coté')], default='X', max_length=1),
        ),
    ]
