# Generated by Django 5.0.7 on 2025-04-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='domain',
        ),
        migrations.AddField(
            model_name='domain',
            name='items',
            field=models.ManyToManyField(related_name='domains', to='categories.item'),
        ),
    ]
