# Generated by Django 5.2 on 2025-08-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileCategory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecategory',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilecategory',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
